const express = require('express');
const cookieParser = require("cookie-parser");
const authRoutes = require("./routes/auth.routes");
const accountRoutes = require("./routes/account.routes");
const transactionRoutes = require("../src/routes/transaction.routes");
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use("/api/auth", authRoutes);
app.use("/api/accounts" ,accountRoutes);
app.use("/api/transaction", transactionRoutes);
module.exports = app;